# Generated by Django 4.0.3 on 2022-03-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='gib',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='modelname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
